config/routes.rb
Seednetworking::Application.routes.draw do
  
  resources :events do
    resources :projects do
      post 'interested'
    end
    resources :participations
  end

  match 'explanation' => "events#explanation"

  devise_for :users
  
  root to: "events#latest"

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  
  SEEKING_OPTIONS = {
    "be_partner" => "Une position d'associe",
    "fulltime_job" => "Un job a plein temps",
    "internship" => "Un stage",
    "contract_job" => "Un contrat de prestation"
  }
  
  belongs_to :event
  belongs_to :user
  
  validates_presence_of :description
  validates_presence_of :user
  validates_presence_of :event
  validates_presence_of :seeking
  
  def seeking
    s = read_attribute(:seeking)
    SEEKING_OPTIONS.has_key?(s) ? I18n.t("seednetworking.participation.seeking_options."+s) : s
  end
  
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  
  before_filter :load_event
  before_filter :authenticate_user!

  # GET /participations/new
  # GET /participations/new.xml
  def new
    authorize! :signup_self, @event
    @participation = Participation.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @participation }
    end
  end

  # GET /participations/1/edit
  def edit
    @participation = Participation.find(params[:id])
    authorize! :update, @participation
  end

  # POST /participations
  # POST /participations.xml
  def create
    authorize! :signup_self, @event
    @participation = Participation.new(params[:participation])
    @participation.seeking ||= params[:seeking_other]
    @participation.event = @event
    @participation.user = current_user
    respond_to do |format|
      if @participation.save
        format.html { redirect_to(@event, :notice => 'Votre participation a bien ete enregistree, n\'oubliez pas de voter pour vos projets favoris') }
        format.xml  { render :xml => @participation, :status => :created, :location => @participation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @participation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /participations/1
  # PUT /participations/1.xml
  def update
    @participation = Participation.find(params[:id])
    authorize! :update, @participation
    respond_to do |format|
      if @participation.update_attributes(params[:participation])
        format.html { redirect_to(@participation, :notice => 'Participation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @participation.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_for([@event, @participation]) do |f| %>
  <% if @participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% @participation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description, size: "30x15" , style:"width:400px"%></td>
      <td></td>
    </tr>
    <tr>
      <td width="100px" vertical-align="top">Je cherche</td>
      <td>
        <% Participation::SEEKING_OPTIONS.each do |k,v| %>
          <%= f.label(("seeking_"+k).to_sym, t("seednetworking.participation.seeking_options."+k))%><%= f.radio_button(:seeking, k)%><br/>
        <% end %>
        <%= label_tag "seeking_other", t("seednetworking.participation.seeking_options.other") %>
        <%= text_field_tag :seeking_other %>
      </td>
      <td></td>
    </tr>
    <tr><td></td>
      <td><%= f.submit %></td><td></td>
    </tr>
  </table>
<% end %>

app/views/participations/edit.html.erb
<h1>Editing participation</h1>

<%= render 'form' %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<h1>Listing participations</h1>

<table>
  <tr>
    <th>Seeking</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participations.each do |participation| %>
  <tr>
    <td><%= participation.seeking %></td>
    <td><%= participation.description %></td>
    <td><%= link_to 'Show', participation %></td>
    <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
    <td><%= link_to 'Destroy', participation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participation', new_participation_path %>

app/views/participations/new.html.erb
<h1><%=t "seednetworking.new_participation.title"%></h1>
<strong><%=tn2br "seednetworking.new_participation.info"%></strong>

<%= render 'form' %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seeking:</b>
  <%= @participation.seeking %>
</p>

<p>
  <b>Description:</b>
  <%= @participation.description %>
</p>


<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>