config/routes.rb
Seednetworking::Application.routes.draw do
  
  resources :events do
    resources :projects do
      post 'interested'
    end
    resources :participations
  end

  match 'explanation' => "events#explanation"

  devise_for :users
  
  root to: "events#latest"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :projects
  has_many :participations
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def latest
    @event = Event.last
    redirect_to @event
  end
  
  def explanation
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/explanation.html.erb
<h1><%=t "seednetworking.how_does_it_work.title"%></h1>
<%=tn2br "seednetworking.how_does_it_work.explanation" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @event.name %></h1>
<h3>Le <%= @event.date %></h3>

<p id="event_description" class='twipsies well'>
  <%= @event.description.gsub(/\n/, "<br/>").html_safe %>
</p>

<p>
<% if can? :signup_project, @event %>
<a href="<%= url_for new_event_project_path(@event) %>" class='btn xlarge success' style="diplay : block;backgound-image:src('http://seednetworking.heroku.com/images/projets.png'); "><%=t "seednetworking.event.signup_project" %> - <%=t "seednetworking.event.signup_project_tagline" %></a>
<% end %><% if can? :signup_self, @event %>
<a href="<%= url_for new_event_participation_path(@event) %>" class='btn xlarge success' style="diplay : block;backgound-image:src('http://seednetworking.heroku.com/images/competences.png');" ><%=t "seednetworking.event.signup_self" %> - <%=t "seednetworking.event.signup_self_tagline" %></a>
<%end%>
</p>

<h2>Liste des projets inscrits:</h2>
<% @event.projects.each do |p| %>
  <hr/>
  <div>
    <h3><%= p.name %></h3>
    <h6>Votes: <%= p.likes.size %></h6>
    <p>
      <%= p.description.gsub(/\n/,"<br/>").html_safe %>
    </p>
    <%= link_to "Voir plus", event_project_path(@event, p) %>
  </div>
<% end %>