config/routes.rb
Seednetworking::Application.routes.draw do
  
  resources :events do
    resources :projects do
      post 'interested'
    end
    resources :participations
  end

  match 'explanation' => "events#explanation"

  devise_for :users
  
  root to: "events#latest"

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  SEEKING_OPTIONS = {
    "partner" => "Un associe",
    "fulltime_worker" => "Un employe plein temps",
    "intern" => "Un stagiare",
    "service_provider" => "Prestataire"
  }
  
  acts_as_votable
  
  belongs_to :event
  belongs_to :user
  
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :user
  validates_presence_of :event
  validates_presence_of :seeking
  
  def seeking
    s = read_attribute(:seeking)
    SEEKING_OPTIONS.has_key?(s) ? I18n.t("seednetworking.project.seeking_options."+s) : s
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :load_event
  before_filter :authenticate_user!, except: [:show]

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    authorize! :read, @project
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
    authorize! :signup_project, @event
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    authorize! :update, @project
  end

  # POST /projects
  # POST /projects.xml
  def create
    authorize! :signup_project, @event
    @project = Project.new(params[:project])
    @project.event = @event
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to([@event, @project], :notice => 'Votre projet a bien ete enregistre') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])
    authorize! :update, @project

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to([@event,@project], :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def interested
    @project = Project.find(params[:project_id])
    authorize! :vote, @project
    
    @project.liked_by current_user
    
    respond_to do |format|  
       format.html { redirect_to([@event, @project], notice: 'Merci pour votre vote !') }  
       format.js   { render :nothing => true }  
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for([@event, @project]) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
  <tr>
    <td width="100px" vertical-align="top"><%= f.label :name, t("seednetworking.new_project.name") %></td>
    <td><%= f.text_field :name %></td>
    <td></td>
  </tr>
  <tr>
    <td><%= f.label :description, t("seednetworking.new_project.description") %></td>
    <td><%= f.text_area :description, size: "30x15" , style:"width:400px"%></td>
    <td>
    </td>
  </tr>
  <tr>
    <td width="100px" vertical-align="top"><%= f.label :website, t("seednetworking.new_project.site") %></td>
    <td><%= f.url_field :website %></td>
    <td></td>
  </tr>
  <tr>
    <td width="100px" vertical-align="top"><%=t("seednetworking.new_project.seeking")%></td>
    <td>
      <% Project::SEEKING_OPTIONS.each do |k,v| %>
        <%= f.label(("seeking_"+k).to_sym, t("seednetworking.project.seeking_options."+k))%><%= f.radio_button(:seeking, k)%><br/>
      <% end %>
      <%= label_tag "seeking_other", t("seednetworking.project.seeking_options.other") %>
      <%= text_field_tag :seeking_other %>
    </td>
    <td></td>
  </tr>
  <tr><td></td>
    <td><%= f.submit %></td><td></td>
  </tr>
</table>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', event_project_path(@event, @project) %>

app/views/projects/new.html.erb
<h1><%=t "seednetworking.new_project.title"%></h1>
<strong><%=tn2br "seednetworking.new_project.info"%></strong>
<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= link_to "Retour à la liste des projets", event_path(@event) %></p>

  <h2><%= @project.name %></h2>
<p>Porté par <%= @project.user.first_name %> <%= @project.user.last_name %></p>
<h3>Le projet</h3>
<% if @project.likes.any? %>
<h4><%= @project.likes.size %> personnes se sont déclarées intéressées par ce projet</h4>
<% end %>
<p>
  <%= @project.description.gsub(/\n/,"<br/>").html_safe %>
</p>

<p>
  <b>Recherche:</b>
  <%= @project.seeking %>
</p>

<p>
  <b>Site web:</b>
  <%= @project.website %>
</p>

<% if can? :vote, @project %>
  <a href='<%= event_project_path(@event, @project)%>/interested' data-method="post" rel='nofollow'> Je suis intéressé par ce projet</a>
<% end %>

<% if can? :edit, @project %>
  <%= link_to "Editez", edit_event_project_path(@event, @project)%>
<% end %>
  